FROM php:7.4-apache

WORKDIR /var/www/html

COPY . .

RUN apt-get update \
    && apt-get install -y libzip-dev \
    && docker-php-ext-install zip \
    && chown -R www-data:www-data storage bootstrap/cache

RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"

CMD ["apache2-foreground"]
